// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class GetMapObjectsResponse;
@class GetMapObjectsResponseBuilder;
@class MapCell;
@class MapCellBuilder;
@class MapPokemon;
@class MapPokemonBuilder;
@class NearbyPokemon;
@class NearbyPokemonBuilder;
@class PokemonData;
@class PokemonDataBuilder;
@class ResponseAuthTicket;
@class ResponseAuthTicketBuilder;
@class ResponseEnvelope;
@class ResponseEnvelopeBuilder;
@class ResponseEnvelopeUnknown6;
@class ResponseEnvelopeUnknown6Builder;
@class ResponseEnvelopeUnknown6Unknown2;
@class ResponseEnvelopeUnknown6Unknown2Builder;
@class ResponseEnvelopeUnknown7;
@class ResponseEnvelopeUnknown7Builder;
@class SpawnPoint;
@class SpawnPointBuilder;
@class WildPokemon;
@class WildPokemonBuilder;


typedef NS_ENUM(SInt32, PokemonId) {
  PokemonIdMissingno = 0,
  PokemonIdBulbasaur = 1,
  PokemonIdIvysaur = 2,
  PokemonIdVenusaur = 3,
  PokemonIdCharmender = 4,
  PokemonIdCharmeleon = 5,
  PokemonIdCharizard = 6,
  PokemonIdSquirtle = 7,
  PokemonIdWartortle = 8,
  PokemonIdBlastoise = 9,
  PokemonIdCaterpie = 10,
  PokemonIdMetapod = 11,
  PokemonIdButterfree = 12,
  PokemonIdWeedle = 13,
  PokemonIdKakuna = 14,
  PokemonIdBeedrill = 15,
  PokemonIdPidgey = 16,
  PokemonIdPidgeotto = 17,
  PokemonIdPidgeot = 18,
  PokemonIdRattata = 19,
  PokemonIdRaticate = 20,
  PokemonIdSpearow = 21,
  PokemonIdFearow = 22,
  PokemonIdEkans = 23,
  PokemonIdArbok = 24,
  PokemonIdPikachu = 25,
  PokemonIdRaichu = 26,
  PokemonIdSandshrew = 27,
  PokemonIdSandlash = 28,
  PokemonIdNidoranFemale = 29,
  PokemonIdNidorina = 30,
  PokemonIdNidoqueen = 31,
  PokemonIdNidoranMale = 32,
  PokemonIdNidorino = 33,
  PokemonIdNidoking = 34,
  PokemonIdClefary = 35,
  PokemonIdClefable = 36,
  PokemonIdVulpix = 37,
  PokemonIdNinetales = 38,
  PokemonIdJigglypuff = 39,
  PokemonIdWigglytuff = 40,
  PokemonIdZubat = 41,
  PokemonIdGolbat = 42,
  PokemonIdOddish = 43,
  PokemonIdGloom = 44,
  PokemonIdVileplume = 45,
  PokemonIdParas = 46,
  PokemonIdParasect = 47,
  PokemonIdVenonat = 48,
  PokemonIdVenomoth = 49,
  PokemonIdDiglett = 50,
  PokemonIdDugtrio = 51,
  PokemonIdMeowth = 52,
  PokemonIdPersian = 53,
  PokemonIdPsyduck = 54,
  PokemonIdGolduck = 55,
  PokemonIdMankey = 56,
  PokemonIdPrimeape = 57,
  PokemonIdGrowlithe = 58,
  PokemonIdArcanine = 59,
  PokemonIdPoliwag = 60,
  PokemonIdPoliwhirl = 61,
  PokemonIdPoliwrath = 62,
  PokemonIdAbra = 63,
  PokemonIdKadabra = 64,
  PokemonIdAlakhazam = 65,
  PokemonIdMachop = 66,
  PokemonIdMachoke = 67,
  PokemonIdMachamp = 68,
  PokemonIdBellsprout = 69,
  PokemonIdWeepinbell = 70,
  PokemonIdVictreebell = 71,
  PokemonIdTentacool = 72,
  PokemonIdTentacruel = 73,
  PokemonIdGeoduge = 74,
  PokemonIdGraveler = 75,
  PokemonIdGolem = 76,
  PokemonIdPonyta = 77,
  PokemonIdRapidash = 78,
  PokemonIdSlowpoke = 79,
  PokemonIdSlowbro = 80,
  PokemonIdMagnemite = 81,
  PokemonIdMagneton = 82,
  PokemonIdFarfetchd = 83,
  PokemonIdDoduo = 84,
  PokemonIdDodrio = 85,
  PokemonIdSeel = 86,
  PokemonIdDewgong = 87,
  PokemonIdGrimer = 88,
  PokemonIdMuk = 89,
  PokemonIdShellder = 90,
  PokemonIdCloyster = 91,
  PokemonIdGastly = 92,
  PokemonIdHaunter = 93,
  PokemonIdGengar = 94,
  PokemonIdOnix = 95,
  PokemonIdDrowzee = 96,
  PokemonIdHypno = 97,
  PokemonIdKrabby = 98,
  PokemonIdKingler = 99,
  PokemonIdVoltorb = 100,
  PokemonIdElectrode = 101,
  PokemonIdExeggcute = 102,
  PokemonIdExeggutor = 103,
  PokemonIdCubone = 104,
  PokemonIdMarowak = 105,
  PokemonIdHitmonlee = 106,
  PokemonIdHitmonchan = 107,
  PokemonIdLickitung = 108,
  PokemonIdKoffing = 109,
  PokemonIdWeezing = 110,
  PokemonIdRhyhorn = 111,
  PokemonIdRhydon = 112,
  PokemonIdChansey = 113,
  PokemonIdTangela = 114,
  PokemonIdKangaskhan = 115,
  PokemonIdHorsea = 116,
  PokemonIdSeadra = 117,
  PokemonIdGoldeen = 118,
  PokemonIdSeaking = 119,
  PokemonIdStaryu = 120,
  PokemonIdStarmie = 121,
  PokemonIdMrMime = 122,
  PokemonIdScyther = 123,
  PokemonIdJynx = 124,
  PokemonIdElectabuzz = 125,
  PokemonIdMagmar = 126,
  PokemonIdPinsir = 127,
  PokemonIdTauros = 128,
  PokemonIdMagikarp = 129,
  PokemonIdGyarados = 130,
  PokemonIdLapras = 131,
  PokemonIdDitto = 132,
  PokemonIdEevee = 133,
  PokemonIdVaporeon = 134,
  PokemonIdJolteon = 135,
  PokemonIdFlareon = 136,
  PokemonIdPorygon = 137,
  PokemonIdOmanyte = 138,
  PokemonIdOmastar = 139,
  PokemonIdKabuto = 140,
  PokemonIdKabutops = 141,
  PokemonIdAerodactyl = 142,
  PokemonIdSnorlax = 143,
  PokemonIdArticuno = 144,
  PokemonIdZapdos = 145,
  PokemonIdMoltres = 146,
  PokemonIdDratini = 147,
  PokemonIdDragonair = 148,
  PokemonIdDragonite = 149,
  PokemonIdMewtwo = 150,
  PokemonIdMew = 151,
};

BOOL PokemonIdIsValidValue(PokemonId value);
NSString *NSStringFromPokemonId(PokemonId value);


@interface ResponseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ResponseEnvelope_status_code @"statusCode"
#define ResponseEnvelope_request_id @"requestId"
#define ResponseEnvelope_api_url @"apiUrl"
#define ResponseEnvelope_unknown6 @"unknown6"
#define ResponseEnvelope_auth_ticket @"authTicket"
#define ResponseEnvelope_returns @"returns"
#define ResponseEnvelope_error @"error"
@interface ResponseEnvelope : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestId_:1;
  BOOL hasStatusCode_:1;
  BOOL hasApiUrl_:1;
  BOOL hasError_:1;
  BOOL hasUnknown6_:1;
  BOOL hasAuthTicket_:1;
  UInt64 requestId;
  SInt32 statusCode;
  NSString* apiUrl;
  NSString* error;
  ResponseEnvelopeUnknown6* unknown6;
  ResponseAuthTicket* authTicket;
  NSMutableArray * returnsArray;
}
- (BOOL) hasStatusCode;
- (BOOL) hasRequestId;
- (BOOL) hasApiUrl;
- (BOOL) hasUnknown6;
- (BOOL) hasAuthTicket;
- (BOOL) hasError;
@property (readonly) SInt32 statusCode;
@property (readonly) UInt64 requestId;
@property (readonly, strong) NSString* apiUrl;
@property (readonly, strong) ResponseEnvelopeUnknown6* unknown6;
@property (readonly, strong) ResponseAuthTicket* authTicket;
@property (readonly, strong) NSArray * returns;
@property (readonly, strong) NSString* error;
- (NSData*)returnsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseEnvelopeBuilder*) builder;
+ (ResponseEnvelopeBuilder*) builder;
+ (ResponseEnvelopeBuilder*) builderWithPrototype:(ResponseEnvelope*) prototype;
- (ResponseEnvelopeBuilder*) toBuilder;

+ (ResponseEnvelope*) parseFromData:(NSData*) data;
+ (ResponseEnvelope*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelope*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseEnvelope*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelope*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseEnvelope*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define Unknown7_unknown71 @"unknown71"
#define Unknown7_unknown72 @"unknown72"
#define Unknown7_unknown73 @"unknown73"
@interface ResponseEnvelopeUnknown7 : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUnknown72_:1;
  BOOL hasUnknown71_:1;
  BOOL hasUnknown73_:1;
  SInt64 unknown72;
  NSData* unknown71;
  NSData* unknown73;
}
- (BOOL) hasUnknown71;
- (BOOL) hasUnknown72;
- (BOOL) hasUnknown73;
@property (readonly, strong) NSData* unknown71;
@property (readonly) SInt64 unknown72;
@property (readonly, strong) NSData* unknown73;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseEnvelopeUnknown7Builder*) builder;
+ (ResponseEnvelopeUnknown7Builder*) builder;
+ (ResponseEnvelopeUnknown7Builder*) builderWithPrototype:(ResponseEnvelopeUnknown7*) prototype;
- (ResponseEnvelopeUnknown7Builder*) toBuilder;

+ (ResponseEnvelopeUnknown7*) parseFromData:(NSData*) data;
+ (ResponseEnvelopeUnknown7*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelopeUnknown7*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseEnvelopeUnknown7*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelopeUnknown7*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseEnvelopeUnknown7*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseEnvelopeUnknown7Builder : PBGeneratedMessageBuilder {
@private
  ResponseEnvelopeUnknown7* resultUnknown7;
}

- (ResponseEnvelopeUnknown7*) defaultInstance;

- (ResponseEnvelopeUnknown7Builder*) clear;
- (ResponseEnvelopeUnknown7Builder*) clone;

- (ResponseEnvelopeUnknown7*) build;
- (ResponseEnvelopeUnknown7*) buildPartial;

- (ResponseEnvelopeUnknown7Builder*) mergeFrom:(ResponseEnvelopeUnknown7*) other;
- (ResponseEnvelopeUnknown7Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseEnvelopeUnknown7Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUnknown71;
- (NSData*) unknown71;
- (ResponseEnvelopeUnknown7Builder*) setUnknown71:(NSData*) value;
- (ResponseEnvelopeUnknown7Builder*) clearUnknown71;

- (BOOL) hasUnknown72;
- (SInt64) unknown72;
- (ResponseEnvelopeUnknown7Builder*) setUnknown72:(SInt64) value;
- (ResponseEnvelopeUnknown7Builder*) clearUnknown72;

- (BOOL) hasUnknown73;
- (NSData*) unknown73;
- (ResponseEnvelopeUnknown7Builder*) setUnknown73:(NSData*) value;
- (ResponseEnvelopeUnknown7Builder*) clearUnknown73;
@end

@interface ResponseEnvelopeBuilder : PBGeneratedMessageBuilder {
@private
  ResponseEnvelope* resultResponseEnvelope;
}

- (ResponseEnvelope*) defaultInstance;

- (ResponseEnvelopeBuilder*) clear;
- (ResponseEnvelopeBuilder*) clone;

- (ResponseEnvelope*) build;
- (ResponseEnvelope*) buildPartial;

- (ResponseEnvelopeBuilder*) mergeFrom:(ResponseEnvelope*) other;
- (ResponseEnvelopeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseEnvelopeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatusCode;
- (SInt32) statusCode;
- (ResponseEnvelopeBuilder*) setStatusCode:(SInt32) value;
- (ResponseEnvelopeBuilder*) clearStatusCode;

- (BOOL) hasRequestId;
- (UInt64) requestId;
- (ResponseEnvelopeBuilder*) setRequestId:(UInt64) value;
- (ResponseEnvelopeBuilder*) clearRequestId;

- (BOOL) hasApiUrl;
- (NSString*) apiUrl;
- (ResponseEnvelopeBuilder*) setApiUrl:(NSString*) value;
- (ResponseEnvelopeBuilder*) clearApiUrl;

- (BOOL) hasUnknown6;
- (ResponseEnvelopeUnknown6*) unknown6;
- (ResponseEnvelopeBuilder*) setUnknown6:(ResponseEnvelopeUnknown6*) value;
- (ResponseEnvelopeBuilder*) setUnknown6Builder:(ResponseEnvelopeUnknown6Builder*) builderForValue;
- (ResponseEnvelopeBuilder*) mergeUnknown6:(ResponseEnvelopeUnknown6*) value;
- (ResponseEnvelopeBuilder*) clearUnknown6;

- (BOOL) hasAuthTicket;
- (ResponseAuthTicket*) authTicket;
- (ResponseEnvelopeBuilder*) setAuthTicket:(ResponseAuthTicket*) value;
- (ResponseEnvelopeBuilder*) setAuthTicketBuilder:(ResponseAuthTicketBuilder*) builderForValue;
- (ResponseEnvelopeBuilder*) mergeAuthTicket:(ResponseAuthTicket*) value;
- (ResponseEnvelopeBuilder*) clearAuthTicket;

- (NSMutableArray *)returns;
- (NSData*)returnsAtIndex:(NSUInteger)index;
- (ResponseEnvelopeBuilder *)addReturns:(NSData*)value;
- (ResponseEnvelopeBuilder *)setReturnsArray:(NSArray *)array;
- (ResponseEnvelopeBuilder *)clearReturns;

- (BOOL) hasError;
- (NSString*) error;
- (ResponseEnvelopeBuilder*) setError:(NSString*) value;
- (ResponseEnvelopeBuilder*) clearError;
@end

#define ResponseAuthTicket_start @"start"
#define ResponseAuthTicket_expire_timestamp_ms @"expireTimestampMs"
#define ResponseAuthTicket_end @"end"
@interface ResponseAuthTicket : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasExpireTimestampMs_:1;
  BOOL hasStart_:1;
  BOOL hasEnd_:1;
  UInt64 expireTimestampMs;
  NSData* start;
  NSData* end;
}
- (BOOL) hasStart;
- (BOOL) hasExpireTimestampMs;
- (BOOL) hasEnd;
@property (readonly, strong) NSData* start;
@property (readonly) UInt64 expireTimestampMs;
@property (readonly, strong) NSData* end;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseAuthTicketBuilder*) builder;
+ (ResponseAuthTicketBuilder*) builder;
+ (ResponseAuthTicketBuilder*) builderWithPrototype:(ResponseAuthTicket*) prototype;
- (ResponseAuthTicketBuilder*) toBuilder;

+ (ResponseAuthTicket*) parseFromData:(NSData*) data;
+ (ResponseAuthTicket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseAuthTicket*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseAuthTicket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseAuthTicket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseAuthTicket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseAuthTicketBuilder : PBGeneratedMessageBuilder {
@private
  ResponseAuthTicket* resultResponseAuthTicket;
}

- (ResponseAuthTicket*) defaultInstance;

- (ResponseAuthTicketBuilder*) clear;
- (ResponseAuthTicketBuilder*) clone;

- (ResponseAuthTicket*) build;
- (ResponseAuthTicket*) buildPartial;

- (ResponseAuthTicketBuilder*) mergeFrom:(ResponseAuthTicket*) other;
- (ResponseAuthTicketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseAuthTicketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStart;
- (NSData*) start;
- (ResponseAuthTicketBuilder*) setStart:(NSData*) value;
- (ResponseAuthTicketBuilder*) clearStart;

- (BOOL) hasExpireTimestampMs;
- (UInt64) expireTimestampMs;
- (ResponseAuthTicketBuilder*) setExpireTimestampMs:(UInt64) value;
- (ResponseAuthTicketBuilder*) clearExpireTimestampMs;

- (BOOL) hasEnd;
- (NSData*) end;
- (ResponseAuthTicketBuilder*) setEnd:(NSData*) value;
- (ResponseAuthTicketBuilder*) clearEnd;
@end

#define ResponseEnvelopeUnknown6_unknown1 @"unknown1"
#define ResponseEnvelopeUnknown6_unknown2 @"unknown2"
@interface ResponseEnvelopeUnknown6 : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUnknown1_:1;
  BOOL hasUnknown2_:1;
  SInt32 unknown1;
  ResponseEnvelopeUnknown6Unknown2* unknown2;
}
- (BOOL) hasUnknown1;
- (BOOL) hasUnknown2;
@property (readonly) SInt32 unknown1;
@property (readonly, strong) ResponseEnvelopeUnknown6Unknown2* unknown2;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseEnvelopeUnknown6Builder*) builder;
+ (ResponseEnvelopeUnknown6Builder*) builder;
+ (ResponseEnvelopeUnknown6Builder*) builderWithPrototype:(ResponseEnvelopeUnknown6*) prototype;
- (ResponseEnvelopeUnknown6Builder*) toBuilder;

+ (ResponseEnvelopeUnknown6*) parseFromData:(NSData*) data;
+ (ResponseEnvelopeUnknown6*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelopeUnknown6*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseEnvelopeUnknown6*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelopeUnknown6*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseEnvelopeUnknown6*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseEnvelopeUnknown6Builder : PBGeneratedMessageBuilder {
@private
  ResponseEnvelopeUnknown6* resultResponseEnvelopeUnknown6;
}

- (ResponseEnvelopeUnknown6*) defaultInstance;

- (ResponseEnvelopeUnknown6Builder*) clear;
- (ResponseEnvelopeUnknown6Builder*) clone;

- (ResponseEnvelopeUnknown6*) build;
- (ResponseEnvelopeUnknown6*) buildPartial;

- (ResponseEnvelopeUnknown6Builder*) mergeFrom:(ResponseEnvelopeUnknown6*) other;
- (ResponseEnvelopeUnknown6Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseEnvelopeUnknown6Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUnknown1;
- (SInt32) unknown1;
- (ResponseEnvelopeUnknown6Builder*) setUnknown1:(SInt32) value;
- (ResponseEnvelopeUnknown6Builder*) clearUnknown1;

- (BOOL) hasUnknown2;
- (ResponseEnvelopeUnknown6Unknown2*) unknown2;
- (ResponseEnvelopeUnknown6Builder*) setUnknown2:(ResponseEnvelopeUnknown6Unknown2*) value;
- (ResponseEnvelopeUnknown6Builder*) setUnknown2Builder:(ResponseEnvelopeUnknown6Unknown2Builder*) builderForValue;
- (ResponseEnvelopeUnknown6Builder*) mergeUnknown2:(ResponseEnvelopeUnknown6Unknown2*) value;
- (ResponseEnvelopeUnknown6Builder*) clearUnknown2;
@end

#define ResponseEnvelopeUnknown6Unknown2_unknown1 @"unknown1"
@interface ResponseEnvelopeUnknown6Unknown2 : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUnknown1_:1;
  NSData* unknown1;
}
- (BOOL) hasUnknown1;
@property (readonly, strong) NSData* unknown1;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseEnvelopeUnknown6Unknown2Builder*) builder;
+ (ResponseEnvelopeUnknown6Unknown2Builder*) builder;
+ (ResponseEnvelopeUnknown6Unknown2Builder*) builderWithPrototype:(ResponseEnvelopeUnknown6Unknown2*) prototype;
- (ResponseEnvelopeUnknown6Unknown2Builder*) toBuilder;

+ (ResponseEnvelopeUnknown6Unknown2*) parseFromData:(NSData*) data;
+ (ResponseEnvelopeUnknown6Unknown2*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelopeUnknown6Unknown2*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseEnvelopeUnknown6Unknown2*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseEnvelopeUnknown6Unknown2*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseEnvelopeUnknown6Unknown2*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseEnvelopeUnknown6Unknown2Builder : PBGeneratedMessageBuilder {
@private
  ResponseEnvelopeUnknown6Unknown2* resultResponseEnvelopeUnknown6Unknown2;
}

- (ResponseEnvelopeUnknown6Unknown2*) defaultInstance;

- (ResponseEnvelopeUnknown6Unknown2Builder*) clear;
- (ResponseEnvelopeUnknown6Unknown2Builder*) clone;

- (ResponseEnvelopeUnknown6Unknown2*) build;
- (ResponseEnvelopeUnknown6Unknown2*) buildPartial;

- (ResponseEnvelopeUnknown6Unknown2Builder*) mergeFrom:(ResponseEnvelopeUnknown6Unknown2*) other;
- (ResponseEnvelopeUnknown6Unknown2Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseEnvelopeUnknown6Unknown2Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUnknown1;
- (NSData*) unknown1;
- (ResponseEnvelopeUnknown6Unknown2Builder*) setUnknown1:(NSData*) value;
- (ResponseEnvelopeUnknown6Unknown2Builder*) clearUnknown1;
@end

#define GetMapObjectsResponse_map_cells @"mapCells"
#define GetMapObjectsResponse_status @"status"
@interface GetMapObjectsResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  SpawnPoint* status;
  NSMutableArray * mapCellsArray;
}
- (BOOL) hasStatus;
@property (readonly, strong) NSArray * mapCells;
@property (readonly, strong) SpawnPoint* status;
- (MapCell*)mapCellsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetMapObjectsResponseBuilder*) builder;
+ (GetMapObjectsResponseBuilder*) builder;
+ (GetMapObjectsResponseBuilder*) builderWithPrototype:(GetMapObjectsResponse*) prototype;
- (GetMapObjectsResponseBuilder*) toBuilder;

+ (GetMapObjectsResponse*) parseFromData:(NSData*) data;
+ (GetMapObjectsResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetMapObjectsResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetMapObjectsResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetMapObjectsResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetMapObjectsResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetMapObjectsResponseBuilder : PBGeneratedMessageBuilder {
@private
  GetMapObjectsResponse* resultGetMapObjectsResponse;
}

- (GetMapObjectsResponse*) defaultInstance;

- (GetMapObjectsResponseBuilder*) clear;
- (GetMapObjectsResponseBuilder*) clone;

- (GetMapObjectsResponse*) build;
- (GetMapObjectsResponse*) buildPartial;

- (GetMapObjectsResponseBuilder*) mergeFrom:(GetMapObjectsResponse*) other;
- (GetMapObjectsResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetMapObjectsResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)mapCells;
- (MapCell*)mapCellsAtIndex:(NSUInteger)index;
- (GetMapObjectsResponseBuilder *)addMapCells:(MapCell*)value;
- (GetMapObjectsResponseBuilder *)setMapCellsArray:(NSArray *)array;
- (GetMapObjectsResponseBuilder *)clearMapCells;

- (BOOL) hasStatus;
- (SpawnPoint*) status;
- (GetMapObjectsResponseBuilder*) setStatus:(SpawnPoint*) value;
- (GetMapObjectsResponseBuilder*) setStatusBuilder:(SpawnPointBuilder*) builderForValue;
- (GetMapObjectsResponseBuilder*) mergeStatus:(SpawnPoint*) value;
- (GetMapObjectsResponseBuilder*) clearStatus;
@end

#define MapCell_s2_cell_id @"s2CellId"
#define MapCell_current_timestamp_ms @"currentTimestampMs"
#define MapCell_forts @"forts"
#define MapCell_spawn_points @"spawnPoints"
#define MapCell_deleted_objects @"deletedObjects"
#define MapCell_is_truncated_list @"isTruncatedList"
#define MapCell_fort_summaries @"fortSummaries"
#define MapCell_decimated_spawn_points @"decimatedSpawnPoints"
#define MapCell_wild_pokemons @"wildPokemons"
#define MapCell_catchable_pokemons @"catchablePokemons"
#define MapCell_nearby_pokemons @"nearbyPokemons"
@interface MapCell : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsTruncatedList_:1;
  BOOL hasCurrentTimestampMs_:1;
  BOOL hasS2CellId_:1;
  BOOL isTruncatedList_:1;
  SInt64 currentTimestampMs;
  UInt64 s2CellId;
  NSMutableArray * deletedObjectsArray;
  NSMutableArray * spawnPointsArray;
  NSMutableArray * decimatedSpawnPointsArray;
  NSMutableArray * wildPokemonsArray;
  NSMutableArray * catchablePokemonsArray;
  NSMutableArray * nearbyPokemonsArray;
  NSMutableArray * fortsArray;
  NSMutableArray * fortSummariesArray;
}
- (BOOL) hasS2CellId;
- (BOOL) hasCurrentTimestampMs;
- (BOOL) hasIsTruncatedList;
@property (readonly) UInt64 s2CellId;
@property (readonly) SInt64 currentTimestampMs;
@property (readonly, strong) NSArray * forts;
@property (readonly, strong) NSArray * spawnPoints;
@property (readonly, strong) NSArray * deletedObjects;
- (BOOL) isTruncatedList;
@property (readonly, strong) NSArray * fortSummaries;
@property (readonly, strong) NSArray * decimatedSpawnPoints;
@property (readonly, strong) NSArray * wildPokemons;
@property (readonly, strong) NSArray * catchablePokemons;
@property (readonly, strong) NSArray * nearbyPokemons;
- (NSData*)fortsAtIndex:(NSUInteger)index;
- (SpawnPoint*)spawnPointsAtIndex:(NSUInteger)index;
- (NSString*)deletedObjectsAtIndex:(NSUInteger)index;
- (NSData*)fortSummariesAtIndex:(NSUInteger)index;
- (SpawnPoint*)decimatedSpawnPointsAtIndex:(NSUInteger)index;
- (WildPokemon*)wildPokemonsAtIndex:(NSUInteger)index;
- (MapPokemon*)catchablePokemonsAtIndex:(NSUInteger)index;
- (NearbyPokemon*)nearbyPokemonsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MapCellBuilder*) builder;
+ (MapCellBuilder*) builder;
+ (MapCellBuilder*) builderWithPrototype:(MapCell*) prototype;
- (MapCellBuilder*) toBuilder;

+ (MapCell*) parseFromData:(NSData*) data;
+ (MapCell*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MapCell*) parseFromInputStream:(NSInputStream*) input;
+ (MapCell*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MapCell*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MapCell*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MapCellBuilder : PBGeneratedMessageBuilder {
@private
  MapCell* resultMapCell;
}

- (MapCell*) defaultInstance;

- (MapCellBuilder*) clear;
- (MapCellBuilder*) clone;

- (MapCell*) build;
- (MapCell*) buildPartial;

- (MapCellBuilder*) mergeFrom:(MapCell*) other;
- (MapCellBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MapCellBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasS2CellId;
- (UInt64) s2CellId;
- (MapCellBuilder*) setS2CellId:(UInt64) value;
- (MapCellBuilder*) clearS2CellId;

- (BOOL) hasCurrentTimestampMs;
- (SInt64) currentTimestampMs;
- (MapCellBuilder*) setCurrentTimestampMs:(SInt64) value;
- (MapCellBuilder*) clearCurrentTimestampMs;

- (NSMutableArray *)forts;
- (NSData*)fortsAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addForts:(NSData*)value;
- (MapCellBuilder *)setFortsArray:(NSArray *)array;
- (MapCellBuilder *)clearForts;

- (NSMutableArray *)spawnPoints;
- (SpawnPoint*)spawnPointsAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addSpawnPoints:(SpawnPoint*)value;
- (MapCellBuilder *)setSpawnPointsArray:(NSArray *)array;
- (MapCellBuilder *)clearSpawnPoints;

- (NSMutableArray *)deletedObjects;
- (NSString*)deletedObjectsAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addDeletedObjects:(NSString*)value;
- (MapCellBuilder *)setDeletedObjectsArray:(NSArray *)array;
- (MapCellBuilder *)clearDeletedObjects;

- (BOOL) hasIsTruncatedList;
- (BOOL) isTruncatedList;
- (MapCellBuilder*) setIsTruncatedList:(BOOL) value;
- (MapCellBuilder*) clearIsTruncatedList;

- (NSMutableArray *)fortSummaries;
- (NSData*)fortSummariesAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addFortSummaries:(NSData*)value;
- (MapCellBuilder *)setFortSummariesArray:(NSArray *)array;
- (MapCellBuilder *)clearFortSummaries;

- (NSMutableArray *)decimatedSpawnPoints;
- (SpawnPoint*)decimatedSpawnPointsAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addDecimatedSpawnPoints:(SpawnPoint*)value;
- (MapCellBuilder *)setDecimatedSpawnPointsArray:(NSArray *)array;
- (MapCellBuilder *)clearDecimatedSpawnPoints;

- (NSMutableArray *)wildPokemons;
- (WildPokemon*)wildPokemonsAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addWildPokemons:(WildPokemon*)value;
- (MapCellBuilder *)setWildPokemonsArray:(NSArray *)array;
- (MapCellBuilder *)clearWildPokemons;

- (NSMutableArray *)catchablePokemons;
- (MapPokemon*)catchablePokemonsAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addCatchablePokemons:(MapPokemon*)value;
- (MapCellBuilder *)setCatchablePokemonsArray:(NSArray *)array;
- (MapCellBuilder *)clearCatchablePokemons;

- (NSMutableArray *)nearbyPokemons;
- (NearbyPokemon*)nearbyPokemonsAtIndex:(NSUInteger)index;
- (MapCellBuilder *)addNearbyPokemons:(NearbyPokemon*)value;
- (MapCellBuilder *)setNearbyPokemonsArray:(NSArray *)array;
- (MapCellBuilder *)clearNearbyPokemons;
@end

#define SpawnPoint_latitude @"latitude"
#define SpawnPoint_longitude @"longitude"
@interface SpawnPoint : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  Float64 latitude;
  Float64 longitude;
}
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
@property (readonly) Float64 latitude;
@property (readonly) Float64 longitude;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SpawnPointBuilder*) builder;
+ (SpawnPointBuilder*) builder;
+ (SpawnPointBuilder*) builderWithPrototype:(SpawnPoint*) prototype;
- (SpawnPointBuilder*) toBuilder;

+ (SpawnPoint*) parseFromData:(NSData*) data;
+ (SpawnPoint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SpawnPoint*) parseFromInputStream:(NSInputStream*) input;
+ (SpawnPoint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SpawnPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SpawnPoint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SpawnPointBuilder : PBGeneratedMessageBuilder {
@private
  SpawnPoint* resultSpawnPoint;
}

- (SpawnPoint*) defaultInstance;

- (SpawnPointBuilder*) clear;
- (SpawnPointBuilder*) clone;

- (SpawnPoint*) build;
- (SpawnPoint*) buildPartial;

- (SpawnPointBuilder*) mergeFrom:(SpawnPoint*) other;
- (SpawnPointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SpawnPointBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (SpawnPointBuilder*) setLatitude:(Float64) value;
- (SpawnPointBuilder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float64) longitude;
- (SpawnPointBuilder*) setLongitude:(Float64) value;
- (SpawnPointBuilder*) clearLongitude;
@end

#define MapPokemon_spawnpoint_id @"spawnpointId"
#define MapPokemon_encounter_id @"encounterId"
#define MapPokemon_pokemon_id @"pokemonId"
#define MapPokemon_expiration_timestamp_ms @"expirationTimestampMs"
#define MapPokemon_latitude @"latitude"
#define MapPokemon_longitude @"longitude"
@interface MapPokemon : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  BOOL hasExpirationTimestampMs_:1;
  BOOL hasEncounterId_:1;
  BOOL hasSpawnpointId_:1;
  BOOL hasPokemonId_:1;
  Float64 latitude;
  Float64 longitude;
  SInt64 expirationTimestampMs;
  UInt64 encounterId;
  NSString* spawnpointId;
  PokemonId pokemonId;
}
- (BOOL) hasSpawnpointId;
- (BOOL) hasEncounterId;
- (BOOL) hasPokemonId;
- (BOOL) hasExpirationTimestampMs;
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
@property (readonly, strong) NSString* spawnpointId;
@property (readonly) UInt64 encounterId;
@property (readonly) PokemonId pokemonId;
@property (readonly) SInt64 expirationTimestampMs;
@property (readonly) Float64 latitude;
@property (readonly) Float64 longitude;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MapPokemonBuilder*) builder;
+ (MapPokemonBuilder*) builder;
+ (MapPokemonBuilder*) builderWithPrototype:(MapPokemon*) prototype;
- (MapPokemonBuilder*) toBuilder;

+ (MapPokemon*) parseFromData:(NSData*) data;
+ (MapPokemon*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MapPokemon*) parseFromInputStream:(NSInputStream*) input;
+ (MapPokemon*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MapPokemon*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MapPokemon*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MapPokemonBuilder : PBGeneratedMessageBuilder {
@private
  MapPokemon* resultMapPokemon;
}

- (MapPokemon*) defaultInstance;

- (MapPokemonBuilder*) clear;
- (MapPokemonBuilder*) clone;

- (MapPokemon*) build;
- (MapPokemon*) buildPartial;

- (MapPokemonBuilder*) mergeFrom:(MapPokemon*) other;
- (MapPokemonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MapPokemonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSpawnpointId;
- (NSString*) spawnpointId;
- (MapPokemonBuilder*) setSpawnpointId:(NSString*) value;
- (MapPokemonBuilder*) clearSpawnpointId;

- (BOOL) hasEncounterId;
- (UInt64) encounterId;
- (MapPokemonBuilder*) setEncounterId:(UInt64) value;
- (MapPokemonBuilder*) clearEncounterId;

- (BOOL) hasPokemonId;
- (PokemonId) pokemonId;
- (MapPokemonBuilder*) setPokemonId:(PokemonId) value;
- (MapPokemonBuilder*) clearPokemonId;

- (BOOL) hasExpirationTimestampMs;
- (SInt64) expirationTimestampMs;
- (MapPokemonBuilder*) setExpirationTimestampMs:(SInt64) value;
- (MapPokemonBuilder*) clearExpirationTimestampMs;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (MapPokemonBuilder*) setLatitude:(Float64) value;
- (MapPokemonBuilder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float64) longitude;
- (MapPokemonBuilder*) setLongitude:(Float64) value;
- (MapPokemonBuilder*) clearLongitude;
@end

#define NearbyPokemon_pokemon_id @"pokemonId"
#define NearbyPokemon_distance_in_meters @"distanceInMeters"
#define NearbyPokemon_encounter_id @"encounterId"
@interface NearbyPokemon : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDistanceInMeters_:1;
  BOOL hasEncounterId_:1;
  BOOL hasPokemonId_:1;
  Float32 distanceInMeters;
  UInt64 encounterId;
  PokemonId pokemonId;
}
- (BOOL) hasPokemonId;
- (BOOL) hasDistanceInMeters;
- (BOOL) hasEncounterId;
@property (readonly) PokemonId pokemonId;
@property (readonly) Float32 distanceInMeters;
@property (readonly) UInt64 encounterId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (NearbyPokemonBuilder*) builder;
+ (NearbyPokemonBuilder*) builder;
+ (NearbyPokemonBuilder*) builderWithPrototype:(NearbyPokemon*) prototype;
- (NearbyPokemonBuilder*) toBuilder;

+ (NearbyPokemon*) parseFromData:(NSData*) data;
+ (NearbyPokemon*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NearbyPokemon*) parseFromInputStream:(NSInputStream*) input;
+ (NearbyPokemon*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NearbyPokemon*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (NearbyPokemon*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface NearbyPokemonBuilder : PBGeneratedMessageBuilder {
@private
  NearbyPokemon* resultNearbyPokemon;
}

- (NearbyPokemon*) defaultInstance;

- (NearbyPokemonBuilder*) clear;
- (NearbyPokemonBuilder*) clone;

- (NearbyPokemon*) build;
- (NearbyPokemon*) buildPartial;

- (NearbyPokemonBuilder*) mergeFrom:(NearbyPokemon*) other;
- (NearbyPokemonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (NearbyPokemonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPokemonId;
- (PokemonId) pokemonId;
- (NearbyPokemonBuilder*) setPokemonId:(PokemonId) value;
- (NearbyPokemonBuilder*) clearPokemonId;

- (BOOL) hasDistanceInMeters;
- (Float32) distanceInMeters;
- (NearbyPokemonBuilder*) setDistanceInMeters:(Float32) value;
- (NearbyPokemonBuilder*) clearDistanceInMeters;

- (BOOL) hasEncounterId;
- (UInt64) encounterId;
- (NearbyPokemonBuilder*) setEncounterId:(UInt64) value;
- (NearbyPokemonBuilder*) clearEncounterId;
@end

#define WildPokemon_encounter_id @"encounterId"
#define WildPokemon_last_modified_timestamp_ms @"lastModifiedTimestampMs"
#define WildPokemon_latitude @"latitude"
#define WildPokemon_longitude @"longitude"
#define WildPokemon_spawnpoint_id @"spawnpointId"
#define WildPokemon_pokemon_data @"pokemonData"
#define WildPokemon_time_till_hidden_ms @"timeTillHiddenMs"
@interface WildPokemon : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  BOOL hasLastModifiedTimestampMs_:1;
  BOOL hasTimeTillHiddenMs_:1;
  BOOL hasEncounterId_:1;
  BOOL hasSpawnpointId_:1;
  BOOL hasPokemonData_:1;
  Float64 latitude;
  Float64 longitude;
  SInt64 lastModifiedTimestampMs;
  SInt32 timeTillHiddenMs;
  UInt64 encounterId;
  NSString* spawnpointId;
  PokemonData* pokemonData;
}
- (BOOL) hasEncounterId;
- (BOOL) hasLastModifiedTimestampMs;
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
- (BOOL) hasSpawnpointId;
- (BOOL) hasPokemonData;
- (BOOL) hasTimeTillHiddenMs;
@property (readonly) UInt64 encounterId;
@property (readonly) SInt64 lastModifiedTimestampMs;
@property (readonly) Float64 latitude;
@property (readonly) Float64 longitude;
@property (readonly, strong) NSString* spawnpointId;
@property (readonly, strong) PokemonData* pokemonData;
@property (readonly) SInt32 timeTillHiddenMs;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WildPokemonBuilder*) builder;
+ (WildPokemonBuilder*) builder;
+ (WildPokemonBuilder*) builderWithPrototype:(WildPokemon*) prototype;
- (WildPokemonBuilder*) toBuilder;

+ (WildPokemon*) parseFromData:(NSData*) data;
+ (WildPokemon*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WildPokemon*) parseFromInputStream:(NSInputStream*) input;
+ (WildPokemon*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WildPokemon*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WildPokemon*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WildPokemonBuilder : PBGeneratedMessageBuilder {
@private
  WildPokemon* resultWildPokemon;
}

- (WildPokemon*) defaultInstance;

- (WildPokemonBuilder*) clear;
- (WildPokemonBuilder*) clone;

- (WildPokemon*) build;
- (WildPokemon*) buildPartial;

- (WildPokemonBuilder*) mergeFrom:(WildPokemon*) other;
- (WildPokemonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WildPokemonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEncounterId;
- (UInt64) encounterId;
- (WildPokemonBuilder*) setEncounterId:(UInt64) value;
- (WildPokemonBuilder*) clearEncounterId;

- (BOOL) hasLastModifiedTimestampMs;
- (SInt64) lastModifiedTimestampMs;
- (WildPokemonBuilder*) setLastModifiedTimestampMs:(SInt64) value;
- (WildPokemonBuilder*) clearLastModifiedTimestampMs;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (WildPokemonBuilder*) setLatitude:(Float64) value;
- (WildPokemonBuilder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float64) longitude;
- (WildPokemonBuilder*) setLongitude:(Float64) value;
- (WildPokemonBuilder*) clearLongitude;

- (BOOL) hasSpawnpointId;
- (NSString*) spawnpointId;
- (WildPokemonBuilder*) setSpawnpointId:(NSString*) value;
- (WildPokemonBuilder*) clearSpawnpointId;

- (BOOL) hasPokemonData;
- (PokemonData*) pokemonData;
- (WildPokemonBuilder*) setPokemonData:(PokemonData*) value;
- (WildPokemonBuilder*) setPokemonDataBuilder:(PokemonDataBuilder*) builderForValue;
- (WildPokemonBuilder*) mergePokemonData:(PokemonData*) value;
- (WildPokemonBuilder*) clearPokemonData;

- (BOOL) hasTimeTillHiddenMs;
- (SInt32) timeTillHiddenMs;
- (WildPokemonBuilder*) setTimeTillHiddenMs:(SInt32) value;
- (WildPokemonBuilder*) clearTimeTillHiddenMs;
@end

#define PokemonData_id @"id"
#define PokemonData_pokemon_id @"pokemonId"
#define PokemonData_cp @"cp"
#define PokemonData_stamina @"stamina"
#define PokemonData_stamina_max @"staminaMax"
#define PokemonData_move_1 @"move1"
#define PokemonData_move_2 @"move2"
#define PokemonData_deployed_fort_id @"deployedFortId"
#define PokemonData_owner_name @"ownerName"
#define PokemonData_is_egg @"isEgg"
#define PokemonData_egg_km_walked_target @"eggKmWalkedTarget"
#define PokemonData_egg_km_walked_start @"eggKmWalkedStart"
#define PokemonData_origin @"origin"
#define PokemonData_height_m @"heightM"
#define PokemonData_weight_kg @"weightKg"
#define PokemonData_individual_attack @"individualAttack"
#define PokemonData_individual_defense @"individualDefense"
#define PokemonData_individual_stamina @"individualStamina"
#define PokemonData_cp_multiplier @"cpMultiplier"
#define PokemonData_pokeball @"pokeball"
#define PokemonData_captured_cell_id @"capturedCellId"
#define PokemonData_battles_attacked @"battlesAttacked"
#define PokemonData_battles_defended @"battlesDefended"
#define PokemonData_egg_incubator_id @"eggIncubatorId"
#define PokemonData_creation_time_ms @"creationTimeMs"
#define PokemonData_num_upgrades @"numUpgrades"
#define PokemonData_additional_cp_multiplier @"additionalCpMultiplier"
#define PokemonData_favorite @"favorite"
#define PokemonData_nickname @"nickname"
#define PokemonData_from_fort @"fromFort"
@interface PokemonData : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsEgg_:1;
  BOOL hasHeightM_:1;
  BOOL hasWeightKg_:1;
  BOOL hasCapturedCellId_:1;
  BOOL hasCreationTimeMs_:1;
  BOOL hasCp_:1;
  BOOL hasStamina_:1;
  BOOL hasStaminaMax_:1;
  BOOL hasDeployedFortId_:1;
  BOOL hasEggKmWalkedTarget_:1;
  BOOL hasEggKmWalkedStart_:1;
  BOOL hasOrigin_:1;
  BOOL hasIndividualAttack_:1;
  BOOL hasIndividualDefense_:1;
  BOOL hasIndividualStamina_:1;
  BOOL hasCpMultiplier_:1;
  BOOL hasPokeball_:1;
  BOOL hasBattlesAttacked_:1;
  BOOL hasBattlesDefended_:1;
  BOOL hasEggIncubatorId_:1;
  BOOL hasNumUpgrades_:1;
  BOOL hasAdditionalCpMultiplier_:1;
  BOOL hasFavorite_:1;
  BOOL hasFromFort_:1;
  BOOL hasId_:1;
  BOOL hasOwnerName_:1;
  BOOL hasNickname_:1;
  BOOL hasMove1_:1;
  BOOL hasMove2_:1;
  BOOL hasPokemonId_:1;
  BOOL isEgg_:1;
  Float32 heightM;
  Float32 weightKg;
  UInt64 capturedCellId;
  UInt64 creationTimeMs;
  SInt32 cp;
  SInt32 stamina;
  SInt32 staminaMax;
  SInt32 deployedFortId;
  SInt32 eggKmWalkedTarget;
  SInt32 eggKmWalkedStart;
  SInt32 origin;
  SInt32 individualAttack;
  SInt32 individualDefense;
  SInt32 individualStamina;
  SInt32 cpMultiplier;
  SInt32 pokeball;
  SInt32 battlesAttacked;
  SInt32 battlesDefended;
  SInt32 eggIncubatorId;
  SInt32 numUpgrades;
  SInt32 additionalCpMultiplier;
  SInt32 favorite;
  SInt32 fromFort;
  UInt64 id;
  NSString* ownerName;
  NSString* nickname;
  NSData* move1;
  NSData* move2;
  PokemonId pokemonId;
}
- (BOOL) hasId;
- (BOOL) hasPokemonId;
- (BOOL) hasCp;
- (BOOL) hasStamina;
- (BOOL) hasStaminaMax;
- (BOOL) hasMove1;
- (BOOL) hasMove2;
- (BOOL) hasDeployedFortId;
- (BOOL) hasOwnerName;
- (BOOL) hasIsEgg;
- (BOOL) hasEggKmWalkedTarget;
- (BOOL) hasEggKmWalkedStart;
- (BOOL) hasOrigin;
- (BOOL) hasHeightM;
- (BOOL) hasWeightKg;
- (BOOL) hasIndividualAttack;
- (BOOL) hasIndividualDefense;
- (BOOL) hasIndividualStamina;
- (BOOL) hasCpMultiplier;
- (BOOL) hasPokeball;
- (BOOL) hasCapturedCellId;
- (BOOL) hasBattlesAttacked;
- (BOOL) hasBattlesDefended;
- (BOOL) hasEggIncubatorId;
- (BOOL) hasCreationTimeMs;
- (BOOL) hasNumUpgrades;
- (BOOL) hasAdditionalCpMultiplier;
- (BOOL) hasFavorite;
- (BOOL) hasNickname;
- (BOOL) hasFromFort;
@property (readonly) UInt64 id;
@property (readonly) PokemonId pokemonId;
@property (readonly) SInt32 cp;
@property (readonly) SInt32 stamina;
@property (readonly) SInt32 staminaMax;
@property (readonly, strong) NSData* move1;
@property (readonly, strong) NSData* move2;
@property (readonly) SInt32 deployedFortId;
@property (readonly, strong) NSString* ownerName;
- (BOOL) isEgg;
@property (readonly) SInt32 eggKmWalkedTarget;
@property (readonly) SInt32 eggKmWalkedStart;
@property (readonly) SInt32 origin;
@property (readonly) Float32 heightM;
@property (readonly) Float32 weightKg;
@property (readonly) SInt32 individualAttack;
@property (readonly) SInt32 individualDefense;
@property (readonly) SInt32 individualStamina;
@property (readonly) SInt32 cpMultiplier;
@property (readonly) SInt32 pokeball;
@property (readonly) UInt64 capturedCellId;
@property (readonly) SInt32 battlesAttacked;
@property (readonly) SInt32 battlesDefended;
@property (readonly) SInt32 eggIncubatorId;
@property (readonly) UInt64 creationTimeMs;
@property (readonly) SInt32 numUpgrades;
@property (readonly) SInt32 additionalCpMultiplier;
@property (readonly) SInt32 favorite;
@property (readonly, strong) NSString* nickname;
@property (readonly) SInt32 fromFort;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PokemonDataBuilder*) builder;
+ (PokemonDataBuilder*) builder;
+ (PokemonDataBuilder*) builderWithPrototype:(PokemonData*) prototype;
- (PokemonDataBuilder*) toBuilder;

+ (PokemonData*) parseFromData:(NSData*) data;
+ (PokemonData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PokemonData*) parseFromInputStream:(NSInputStream*) input;
+ (PokemonData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PokemonData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PokemonData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PokemonDataBuilder : PBGeneratedMessageBuilder {
@private
  PokemonData* resultPokemonData;
}

- (PokemonData*) defaultInstance;

- (PokemonDataBuilder*) clear;
- (PokemonDataBuilder*) clone;

- (PokemonData*) build;
- (PokemonData*) buildPartial;

- (PokemonDataBuilder*) mergeFrom:(PokemonData*) other;
- (PokemonDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PokemonDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt64) id;
- (PokemonDataBuilder*) setId:(UInt64) value;
- (PokemonDataBuilder*) clearId;

- (BOOL) hasPokemonId;
- (PokemonId) pokemonId;
- (PokemonDataBuilder*) setPokemonId:(PokemonId) value;
- (PokemonDataBuilder*) clearPokemonId;

- (BOOL) hasCp;
- (SInt32) cp;
- (PokemonDataBuilder*) setCp:(SInt32) value;
- (PokemonDataBuilder*) clearCp;

- (BOOL) hasStamina;
- (SInt32) stamina;
- (PokemonDataBuilder*) setStamina:(SInt32) value;
- (PokemonDataBuilder*) clearStamina;

- (BOOL) hasStaminaMax;
- (SInt32) staminaMax;
- (PokemonDataBuilder*) setStaminaMax:(SInt32) value;
- (PokemonDataBuilder*) clearStaminaMax;

- (BOOL) hasMove1;
- (NSData*) move1;
- (PokemonDataBuilder*) setMove1:(NSData*) value;
- (PokemonDataBuilder*) clearMove1;

- (BOOL) hasMove2;
- (NSData*) move2;
- (PokemonDataBuilder*) setMove2:(NSData*) value;
- (PokemonDataBuilder*) clearMove2;

- (BOOL) hasDeployedFortId;
- (SInt32) deployedFortId;
- (PokemonDataBuilder*) setDeployedFortId:(SInt32) value;
- (PokemonDataBuilder*) clearDeployedFortId;

- (BOOL) hasOwnerName;
- (NSString*) ownerName;
- (PokemonDataBuilder*) setOwnerName:(NSString*) value;
- (PokemonDataBuilder*) clearOwnerName;

- (BOOL) hasIsEgg;
- (BOOL) isEgg;
- (PokemonDataBuilder*) setIsEgg:(BOOL) value;
- (PokemonDataBuilder*) clearIsEgg;

- (BOOL) hasEggKmWalkedTarget;
- (SInt32) eggKmWalkedTarget;
- (PokemonDataBuilder*) setEggKmWalkedTarget:(SInt32) value;
- (PokemonDataBuilder*) clearEggKmWalkedTarget;

- (BOOL) hasEggKmWalkedStart;
- (SInt32) eggKmWalkedStart;
- (PokemonDataBuilder*) setEggKmWalkedStart:(SInt32) value;
- (PokemonDataBuilder*) clearEggKmWalkedStart;

- (BOOL) hasOrigin;
- (SInt32) origin;
- (PokemonDataBuilder*) setOrigin:(SInt32) value;
- (PokemonDataBuilder*) clearOrigin;

- (BOOL) hasHeightM;
- (Float32) heightM;
- (PokemonDataBuilder*) setHeightM:(Float32) value;
- (PokemonDataBuilder*) clearHeightM;

- (BOOL) hasWeightKg;
- (Float32) weightKg;
- (PokemonDataBuilder*) setWeightKg:(Float32) value;
- (PokemonDataBuilder*) clearWeightKg;

- (BOOL) hasIndividualAttack;
- (SInt32) individualAttack;
- (PokemonDataBuilder*) setIndividualAttack:(SInt32) value;
- (PokemonDataBuilder*) clearIndividualAttack;

- (BOOL) hasIndividualDefense;
- (SInt32) individualDefense;
- (PokemonDataBuilder*) setIndividualDefense:(SInt32) value;
- (PokemonDataBuilder*) clearIndividualDefense;

- (BOOL) hasIndividualStamina;
- (SInt32) individualStamina;
- (PokemonDataBuilder*) setIndividualStamina:(SInt32) value;
- (PokemonDataBuilder*) clearIndividualStamina;

- (BOOL) hasCpMultiplier;
- (SInt32) cpMultiplier;
- (PokemonDataBuilder*) setCpMultiplier:(SInt32) value;
- (PokemonDataBuilder*) clearCpMultiplier;

- (BOOL) hasPokeball;
- (SInt32) pokeball;
- (PokemonDataBuilder*) setPokeball:(SInt32) value;
- (PokemonDataBuilder*) clearPokeball;

- (BOOL) hasCapturedCellId;
- (UInt64) capturedCellId;
- (PokemonDataBuilder*) setCapturedCellId:(UInt64) value;
- (PokemonDataBuilder*) clearCapturedCellId;

- (BOOL) hasBattlesAttacked;
- (SInt32) battlesAttacked;
- (PokemonDataBuilder*) setBattlesAttacked:(SInt32) value;
- (PokemonDataBuilder*) clearBattlesAttacked;

- (BOOL) hasBattlesDefended;
- (SInt32) battlesDefended;
- (PokemonDataBuilder*) setBattlesDefended:(SInt32) value;
- (PokemonDataBuilder*) clearBattlesDefended;

- (BOOL) hasEggIncubatorId;
- (SInt32) eggIncubatorId;
- (PokemonDataBuilder*) setEggIncubatorId:(SInt32) value;
- (PokemonDataBuilder*) clearEggIncubatorId;

- (BOOL) hasCreationTimeMs;
- (UInt64) creationTimeMs;
- (PokemonDataBuilder*) setCreationTimeMs:(UInt64) value;
- (PokemonDataBuilder*) clearCreationTimeMs;

- (BOOL) hasNumUpgrades;
- (SInt32) numUpgrades;
- (PokemonDataBuilder*) setNumUpgrades:(SInt32) value;
- (PokemonDataBuilder*) clearNumUpgrades;

- (BOOL) hasAdditionalCpMultiplier;
- (SInt32) additionalCpMultiplier;
- (PokemonDataBuilder*) setAdditionalCpMultiplier:(SInt32) value;
- (PokemonDataBuilder*) clearAdditionalCpMultiplier;

- (BOOL) hasFavorite;
- (SInt32) favorite;
- (PokemonDataBuilder*) setFavorite:(SInt32) value;
- (PokemonDataBuilder*) clearFavorite;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (PokemonDataBuilder*) setNickname:(NSString*) value;
- (PokemonDataBuilder*) clearNickname;

- (BOOL) hasFromFort;
- (SInt32) fromFort;
- (PokemonDataBuilder*) setFromFort:(SInt32) value;
- (PokemonDataBuilder*) clearFromFort;
@end


// @@protoc_insertion_point(global_scope)
